version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq
    hostname: rabbitmq
    command: rabbitmq-server
    ports:
      - "8000:15672"
      - "8001:5672"
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge