version: '3.8'
services:
# Absence Service
  absenceServiceDatabase:
    image: mysql:8.0.33
    container_name: WebAppDemo.AbsenceService.Database
    hostname: WebAppDemo.AbsenceService.Database
    environment:
        - ACCEPT_EULA='Y'
        - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    ports:
        - "8003:3306"
    networks:
      - absenceServiceDatabase_net
  absenceService:
    image: webappdemoabsenceservice:dev
    container_name: WebAppDemo.AbsenceService.Api
    hostname: WebAppDemo.AbsenceService.Api
    build:
      context: ./AbsenceService
      dockerfile: Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      absenceServiceDatabase:
        condition: service_healthy
    ports:
      - "8002:80"
    networks:
      - absenceService_net
# Message Bus
  rabbitmq:
   image: rabbitmq:3.12.1-management
   container_name: rabbitmq
   hostname: rabbitmq
   command: rabbitmq-server
   ports:
     - "8000:15672"
     - "8001:5672"
   networks:
       - rabbitmq_net
# API Gateaway
  apiGateway:
    image: webappdemoapigateway:dev
    container_name: WebAppDemo.ApiGateway
    hostname: WebAppDemo.ApiGateway
    build:
      context: ./WebAppDemo.ApiGateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports: 
      - "8004:80"
    networks:
      - apiGateway_net

networks:
  rabbitmq_net:
    driver: bridge
  absenceService_net:
    driver: bridge
  absenceServiceDatabase_net:
    driver: bridge  
  apiGateway_net:
    driver: bridge